"""
Appendix Generators for Specification Documents

This module provides generators for appendix sections in Requirements.md,
Design.md, and Implementation.md documents.
"""

from typing import List

from ..audit_models import AuditResult


class RequirementsAppendixGenerator:
    """Generates appendix section for Requirements.md."""

    @staticmethod
    def generate(audit_result: AuditResult) -> List[str]:
        """
        Generate appendix with technical details for Requirements.md.

        Args:
            audit_result: Complete audit results

        Returns:
            List of markdown lines for the appendix section
        """
        content = []
        content.append("## Appendix")
        content.append("")

        # Analysis configuration
        content.append("### Analysis Configuration")
        content.append("")
        metadata = audit_result.analysis_metadata
        content.append("| Setting | Value |")
        content.append("|---------|-------|")
        content.append(f"| Include Index | {metadata.get('include_index', 'N/A')} |")
        content.append(f"| Include Duplicates | {metadata.get('include_duplicates', 'N/A')} |")
        content.append(f"| Include Unused | {metadata.get('include_unused', 'N/A')} |")
        content.append(f"| Min Confidence | {metadata.get('min_confidence', 'N/A')} |")
        content.append(f"| Incremental Index | {metadata.get('incremental_index', 'N/A')} |")
        content.append("")

        # Index statistics
        if audit_result.index_result:
            content.append("### Index Statistics")
            content.append("")
            idx = audit_result.index_result
            content.append("| Metric | Value |")
            content.append("|--------|-------|")
            content.append(f"| Files Processed | {idx.files_processed} |")
            content.append(f"| Files Skipped | {idx.files_skipped} |")
            content.append(f"| Symbols Found | {idx.symbols_found} |")
            content.append(f"| Blocks Found | {idx.blocks_found} |")
            content.append(f"| Dependencies Found | {idx.dependencies_found} |")
            content.append(f"| Build Time | {idx.build_time_seconds:.2f}s |")
            content.append(f"| Incremental | {idx.incremental} |")
            content.append("")

        # Unused code statistics
        if audit_result.unused_result:
            content.append("### Unused Code Statistics")
            content.append("")
            unused_stats = audit_result.unused_result.statistics
            content.append("| Metric | Value |")
            content.append("|--------|-------|")
            content.append(f"| Total Findings | {unused_stats.get('total_findings', 0)} |")
            content.append(f"| Files Analyzed | {unused_stats.get('total_files_analyzed', 0)} |")
            content.append(f"| Entry Points | {len(audit_result.unused_result.entry_points)} |")
            content.append("")

            # Entry points
            if audit_result.unused_result.entry_points:
                content.append("**Entry Points:**")
                for entry_point in audit_result.unused_result.entry_points:
                    content.append(f"- `{entry_point}`")
                content.append("")

        # Clone detection statistics
        if audit_result.clone_groups:
            content.append("### Clone Detection Statistics")
            content.append("")
            content.append("| Metric | Value |")
            content.append("|--------|-------|")
            content.append(f"| Clone Groups | {len(audit_result.clone_groups)} |")

            total_instances = sum(len(group.instances) for group in audit_result.clone_groups)
            content.append(f"| Total Instances | {total_instances} |")

            if audit_result.clone_groups:
                avg_similarity = sum(
                    group.similarity_score for group in audit_result.clone_groups
                ) / len(audit_result.clone_groups)
                content.append(f"| Average Similarity | {avg_similarity:.3f} |")

            content.append("")

        # Tool information
        content.append("### Tool Information")
        content.append("")
        content.append(
            "This report was generated by **IntelliRefactor** - Intelligent Project Analysis and Refactoring System."
        )
        content.append("")
        content.append("**Analysis Components:**")
        content.append("- Persistent Index Builder")
        content.append("- Block-level Clone Detector")
        content.append("- Three-level Unused Code Detector")
        content.append("- Evidence-based Analysis Engine")
        content.append("")
        content.append(
            "For more information, visit: https://github.com/intellirefactor/intellirefactor"
        )
        content.append("")

        return content


class DesignAppendixGenerator:
    """Generates appendix section for Design.md."""

    @staticmethod
    def generate(audit_result: AuditResult) -> List[str]:
        """
        Generate appendix for Design.md.

        Args:
            audit_result: Complete audit results

        Returns:
            List of markdown lines for the appendix section
        """
        content = []
        content.append("## Appendix")
        content.append("")

        # Design patterns and principles
        content.append("### Design Patterns and Principles")
        content.append("")
        content.append("**Recommended Patterns:**")
        content.append("- Strategy Pattern for algorithm variations")
        content.append("- Factory Pattern for object creation")
        content.append("- Observer Pattern for event handling")
        content.append("- Dependency Injection for loose coupling")
        content.append("")

        content.append("**SOLID Principles:**")
        content.append("- Single Responsibility: One class, one purpose")
        content.append("- Open/Closed: Open for extension, closed for modification")
        content.append("- Liskov Substitution: Subtypes must be substitutable")
        content.append("- Interface Segregation: Many specific interfaces over one general")
        content.append("- Dependency Inversion: Depend on abstractions, not concretions")
        content.append("")

        # References
        content.append("### References")
        content.append("")
        content.append("**Books:**")
        content.append("- *Refactoring* by Martin Fowler")
        content.append("- *Clean Code* by Robert C. Martin")
        content.append("- *Design Patterns* by Gang of Four")
        content.append("")

        content.append("**Online Resources:**")
        content.append("- Refactoring Guru: https://refactoring.guru")
        content.append("- Martin Fowler's Refactoring Catalog: https://refactoring.com")
        content.append("")

        return content


class ImplementationAppendixGenerator:
    """Generates appendix section for Implementation.md."""

    @staticmethod
    def generate(audit_result: AuditResult) -> List[str]:
        """
        Generate appendix for Implementation.md.

        Args:
            audit_result: Complete audit results

        Returns:
            List of markdown lines for the appendix section
        """
        content = []
        content.append("## Appendix")
        content.append("")

        # Tools and resources
        content.append("### Tools and Resources")
        content.append("")
        content.append("**Development Tools:**")
        content.append("- IntelliRefactor for automated analysis")
        content.append("- Git for version control and rollback")
        content.append("- IDE with refactoring support")
        content.append("- Code coverage tools")
        content.append("- Performance profiling tools")
        content.append("")

        content.append("**Testing Tools:**")
        content.append("- Unit testing framework")
        content.append("- Integration testing tools")
        content.append("- Code quality analyzers")
        content.append("- Automated testing pipeline")
        content.append("")

        # Best practices
        content.append("### Refactoring Best Practices")
        content.append("")
        content.append("**General Principles:**")
        content.append("- Make small, incremental changes")
        content.append("- Test frequently and thoroughly")
        content.append("- Preserve existing behavior")
        content.append("- Improve design without changing functionality")
        content.append("")

        content.append("**Code Extraction:**")
        content.append("- Extract methods before extracting classes")
        content.append("- Use meaningful names for extracted elements")
        content.append("- Minimize parameter lists")
        content.append("- Maintain single responsibility principle")
        content.append("")

        content.append("**Cleanup Guidelines:**")
        content.append("- Remove unused imports and variables")
        content.append("- Eliminate dead code paths")
        content.append("- Simplify complex conditional logic")
        content.append("- Reduce nesting levels")
        content.append("")

        # Timeline template
        content.append("### Implementation Timeline Template")
        content.append("")

        total_findings = audit_result.statistics.total_findings
        if total_findings > 0:
            # Estimate timeline based on findings
            critical_count = audit_result.statistics.findings_by_severity.get("critical", 0)
            high_count = audit_result.statistics.findings_by_severity.get("high", 0)

            content.append("**Week 1:**")
            if critical_count > 0:
                content.append("- Days 1-2: Address critical issues")
                content.append("- Days 3-5: Begin high priority refactoring")
            else:
                content.append("- Days 1-5: High priority refactoring")
            content.append("")

            content.append("**Week 2:**")
            content.append("- Days 1-3: Continue refactoring work")
            content.append("- Days 4-5: Testing and validation")
            content.append("")

            if total_findings > 20:
                content.append("**Week 3:**")
                content.append("- Days 1-3: Medium priority improvements")
                content.append("- Days 4-5: Final testing and documentation")
                content.append("")
        else:
            content.append(
                "**No implementation timeline needed - codebase is in excellent condition!**"
            )
            content.append("")

        return content
